[project]
name = "stx-semi-fungible-token"
requirements = []
costs_version = 1
[contracts.clash-of-clans-alike]
path = "contracts/clash-of-clans-alike.clar"
depends_on = ["sipxxx-semi-fungible-token-trait"]

[contracts.semi-fungible-token]
path = "contracts/semi-fungible-token.clar"
depends_on = ["sipxxx-semi-fungible-token-trait"]

[contracts.sip010-ft-trait]
path = "contracts/test/sip010-ft-trait.clar"
depends_on = []

[contracts.sipxxx-semi-fungible-token-trait]
path = "contracts/sipxxx-semi-fungible-token-trait.clar"
depends_on = []

[contracts.test-sip010]
path = "contracts/test/test-sip010.clar"
depends_on = ["sip010-ft-trait"]

[contracts.wrapped-sip010-sft]
path = "contracts/wrapped-sip010-sft.clar"
depends_on = ["sipxxx-semi-fungible-token-trait"]
